import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        primary: '#005bbf',
        'primary-container': '#1a73e8',
        'primary-fixed': '#d8e2ff',
        'primary-fixed-dim': '#adc7ff',
        'on-primary': '#ffffff',
        'on-primary-fixed': '#001a41',
        'on-primary-fixed-variant': '#004493',
        secondary: '#006e2c',
        'secondary-container': '#86f898',
        'secondary-fixed-dim': '#6ddd81',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#00722f',
        tertiary: '#795900',
        'tertiary-fixed': '#ffdfa0',
        'tertiary-fixed-dim': '#fbbc05',
        'on-tertiary': '#ffffff',
        'on-tertiary-fixed': '#261a00',
        'on-tertiary-fixed-variant': '#5c4300',
        'on-tertiary-container': '#ffffff',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        background: '#f7f9ff',
        'on-background': '#181c20',
        surface: '#f7f9ff',
        'surface-dim': '#d7dae0',
        'surface-bright': '#f7f9ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f1f4fa',
        'surface-container': '#ebeef4',
        'surface-container-high': '#e5e8ee',
        'surface-container-highest': '#dfe3e8',
        'surface-variant': '#dfe3e8',
        'on-surface': '#181c20',
        'on-surface-variant': '#414754',
        outline: '#727785',
        'outline-variant': '#c1c6d6',
        'inverse-surface': '#2d3135',
        'inverse-on-surface': '#eef1f7',
        'inverse-primary': '#adc7ff',
        'surface-tint': '#005bc0',
      },
      fontFamily: {
        sans: ['Inter', 'Sarabun', 'sans-serif'],
      },
      borderRadius: {
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
      },
    },
  },
  plugins: [],
};

export default config;
